apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
  labels:
    some-label: pod
spec:
  containers:
    - name: maven
      image: maven:3.3.9-jdk-8-alpine
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /Users/zhangjie/.m2/repository
    - name: docker
      image: docker:20.10.14
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /Users/zhangjie/devops/jenkins/pipeline/run/docker.sock
    - name: helm
      image: lachlanevenson/k8s-helm:v3.10.2
      command:
        - cat
      tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /Users/zhangjie/devops/jenkins/pipeline/run/docker.sock
    - name: m2
      hostPath:
        path: /Users/zhangjie/.m2/repository